# Generated by Django 5.2.4 on 2025-07-08 01:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("timestamp", models.DateTimeField(unique=True)),
                (
                    "total_market_volume",
                    models.DecimalField(decimal_places=8, max_digits=20),
                ),
                ("active_trading_pairs", models.IntegerField()),
                ("active_exchanges", models.IntegerField()),
                ("active_opportunities", models.IntegerField()),
                (
                    "average_spread",
                    models.DecimalField(decimal_places=4, max_digits=10),
                ),
                ("max_spread", models.DecimalField(decimal_places=4, max_digits=10)),
                (
                    "top_opportunities",
                    models.JSONField(
                        default=list,
                        help_text="List of top arbitrage opportunities at this moment",
                    ),
                ),
                (
                    "market_trend",
                    models.CharField(
                        choices=[
                            ("bullish", "Bullish"),
                            ("bearish", "Bearish"),
                            ("neutral", "Neutral"),
                            ("volatile", "Volatile"),
                        ],
                        default="neutral",
                        max_length=20,
                    ),
                ),
                (
                    "exchange_status",
                    models.JSONField(
                        default=dict,
                        help_text="Status of each exchange at snapshot time",
                    ),
                ),
            ],
            options={
                "verbose_name": "Market Snapshot",
                "verbose_name_plural": "Market Snapshots",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="DailyArbitrageSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField(unique=True)),
                ("total_opportunities", models.IntegerField(default=0)),
                ("total_executions", models.IntegerField(default=0)),
                ("successful_executions", models.IntegerField(default=0)),
                ("failed_executions", models.IntegerField(default=0)),
                (
                    "total_profit",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
                (
                    "average_profit_percentage",
                    models.DecimalField(decimal_places=4, default=0, max_digits=10),
                ),
                (
                    "highest_profit_percentage",
                    models.DecimalField(decimal_places=4, default=0, max_digits=10),
                ),
                ("top_route", models.JSONField(default=dict)),
                (
                    "total_volume_traded",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
                (
                    "market_volatility_index",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "top_trading_pair",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="daily_summaries",
                        to="core.tradingpair",
                    ),
                ),
            ],
            options={
                "verbose_name": "Daily Arbitrage Summary",
                "verbose_name_plural": "Daily Arbitrage Summaries",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="ExchangePerformance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField()),
                (
                    "uptime_percentage",
                    models.DecimalField(decimal_places=2, default=100, max_digits=5),
                ),
                (
                    "average_response_time",
                    models.FloatField(help_text="Average API response time in seconds"),
                ),
                ("error_count", models.IntegerField(default=0)),
                ("total_orders_placed", models.IntegerField(default=0)),
                ("successful_orders", models.IntegerField(default=0)),
                ("failed_orders", models.IntegerField(default=0)),
                ("opportunities_as_buy", models.IntegerField(default=0)),
                ("opportunities_as_sell", models.IntegerField(default=0)),
                (
                    "total_volume",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
                (
                    "exchange",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance_metrics",
                        to="core.exchange",
                    ),
                ),
            ],
            options={
                "verbose_name": "Exchange Performance",
                "verbose_name_plural": "Exchange Performances",
                "ordering": ["-date", "exchange"],
                "unique_together": {("exchange", "date")},
            },
        ),
        migrations.CreateModel(
            name="TradingPairAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("period_start", models.DateTimeField()),
                ("period_end", models.DateTimeField()),
                (
                    "period_type",
                    models.CharField(
                        choices=[
                            ("hourly", "Hourly"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        max_length=20,
                    ),
                ),
                ("total_opportunities", models.IntegerField(default=0)),
                (
                    "average_spread_percentage",
                    models.DecimalField(decimal_places=4, default=0, max_digits=10),
                ),
                (
                    "max_spread_percentage",
                    models.DecimalField(decimal_places=4, default=0, max_digits=10),
                ),
                ("total_executions", models.IntegerField(default=0)),
                (
                    "success_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "average_profit",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
                (
                    "total_volume",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
                (
                    "price_volatility",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "average_price",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=20, null=True
                    ),
                ),
                ("top_routes", models.JSONField(default=list)),
                (
                    "trading_pair",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="core.tradingpair",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trading Pair Analytics",
                "verbose_name_plural": "Trading Pair Analytics",
                "ordering": ["-period_start"],
                "indexes": [
                    models.Index(
                        fields=["trading_pair", "period_type", "-period_start"],
                        name="analytics_t_trading_6a3c1f_idx",
                    )
                ],
                "unique_together": {("trading_pair", "period_start", "period_type")},
            },
        ),
        migrations.CreateModel(
            name="UserPerformance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField()),
                ("total_executions", models.IntegerField(default=0)),
                ("successful_executions", models.IntegerField(default=0)),
                ("failed_executions", models.IntegerField(default=0)),
                (
                    "daily_profit",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
                (
                    "daily_loss",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
                (
                    "net_profit",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
                (
                    "roi_percentage",
                    models.DecimalField(decimal_places=4, default=0, max_digits=10),
                ),
                (
                    "total_volume_traded",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
                (
                    "total_fees_paid",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
                (
                    "max_drawdown",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "sharpe_ratio",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance_metrics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Performance",
                "verbose_name_plural": "User Performances",
                "ordering": ["-date"],
                "unique_together": {("user", "date")},
            },
        ),
    ]
