# Generated by Django 5.2.4 on 2025-07-08 02:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExchangeStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_online", models.BooleanField(default=True)),
                ("last_check", models.DateTimeField(auto_now=True)),
                (
                    "response_time",
                    models.FloatField(help_text="Response time in seconds", null=True),
                ),
                ("error_count", models.IntegerField(default=0)),
                ("last_error", models.TextField(blank=True)),
                ("last_error_time", models.DateTimeField(null=True)),
                (
                    "exchange",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status",
                        to="core.exchange",
                    ),
                ),
            ],
            options={
                "verbose_name": "Exchange Status",
                "verbose_name_plural": "Exchange Statuses",
            },
        ),
        migrations.CreateModel(
            name="OrderBook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("timestamp", models.DateTimeField(db_index=True)),
                (
                    "exchange_pair",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_books",
                        to="core.exchangetradingpair",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order Book",
                "verbose_name_plural": "Order Books",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="OrderBookEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "side",
                    models.CharField(
                        choices=[("bid", "Bid"), ("ask", "Ask")], max_length=3
                    ),
                ),
                ("price", models.DecimalField(decimal_places=8, max_digits=20)),
                ("amount", models.DecimalField(decimal_places=8, max_digits=20)),
                ("total", models.DecimalField(decimal_places=8, max_digits=20)),
                ("position", models.IntegerField()),
                (
                    "order_book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="exchanges.orderbook",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order Book Entry",
                "verbose_name_plural": "Order Book Entries",
                "ordering": ["position"],
            },
        ),
        migrations.CreateModel(
            name="ExchangeBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "available",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
                (
                    "locked",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exchange_balances",
                        to="core.currency",
                    ),
                ),
                (
                    "exchange",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_balances",
                        to="core.exchange",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exchange_balances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Exchange Balance",
                "verbose_name_plural": "Exchange Balances",
                "ordering": ["exchange", "currency"],
                "unique_together": {("user", "exchange", "currency")},
            },
        ),
        migrations.CreateModel(
            name="MarketTicker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("timestamp", models.DateTimeField(db_index=True)),
                ("last_price", models.DecimalField(decimal_places=8, max_digits=20)),
                (
                    "bid_price",
                    models.DecimalField(decimal_places=8, max_digits=20, null=True),
                ),
                (
                    "ask_price",
                    models.DecimalField(decimal_places=8, max_digits=20, null=True),
                ),
                ("volume_24h", models.DecimalField(decimal_places=8, max_digits=20)),
                ("high_24h", models.DecimalField(decimal_places=8, max_digits=20)),
                ("low_24h", models.DecimalField(decimal_places=8, max_digits=20)),
                ("change_24h", models.DecimalField(decimal_places=4, max_digits=10)),
                (
                    "exchange_pair",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickers",
                        to="core.exchangetradingpair",
                    ),
                ),
            ],
            options={
                "verbose_name": "Market Ticker",
                "verbose_name_plural": "Market Tickers",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["exchange_pair", "-timestamp"],
                        name="exchanges_m_exchang_34d636_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="orderbook",
            index=models.Index(
                fields=["exchange_pair", "-timestamp"],
                name="exchanges_o_exchang_707722_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="orderbookentry",
            index=models.Index(
                fields=["order_book", "side", "position"],
                name="exchanges_o_order_b_d03bda_idx",
            ),
        ),
    ]
