# Generated by Django 5.2.4 on 2025-07-08 02:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("telegram_id", models.CharField(blank=True, max_length=100)),
                ("enable_email_alerts", models.BooleanField(default=True)),
                ("enable_telegram_alerts", models.BooleanField(default=False)),
                ("enable_push_notifications", models.BooleanField(default=False)),
                ("timezone", models.CharField(default="UTC", max_length=50)),
                ("language", models.CharField(default="en", max_length=10)),
                ("daily_trade_count", models.IntegerField(default=0)),
                ("last_trade_reset", models.DateTimeField(blank=True, null=True)),
                (
                    "default_exchange",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="default_for_users",
                        to="core.exchange",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
            },
        ),
        migrations.CreateModel(
            name="NotificationSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("opportunity_detected", "Arbitrage Opportunity Detected"),
                            ("execution_started", "Execution Started"),
                            ("execution_completed", "Execution Completed"),
                            ("execution_failed", "Execution Failed"),
                            ("high_profit", "High Profit Opportunity"),
                            ("order_filled", "Order Filled"),
                            ("position_closed", "Position Closed"),
                            ("stop_loss_hit", "Stop Loss Hit"),
                            ("low_balance", "Low Balance Warning"),
                        ],
                        max_length=30,
                    ),
                ),
                ("email_enabled", models.BooleanField(default=True)),
                ("telegram_enabled", models.BooleanField(default=False)),
                ("push_enabled", models.BooleanField(default=False)),
                (
                    "min_profit_percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Only notify if profit % is above this",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Setting",
                "verbose_name_plural": "Notification Settings",
                "unique_together": {("user", "notification_type")},
            },
        ),
    ]
